stages:
  - build
  - package
  - deploy

variables:
  # CI VARIABLES
  CI_REGISTRY_USER: hendrik.nurfuad
  CI_REGISTRY_PASSWORD: 1RYdzv7i6xepZTjH1xHu
  CI_REGISTRY: registry-iconx.air.id

  # DATASOURCE LOKI
  DATASOURCE_LOKI: http://10.14.204.239/log/loki/loki/api/v1/push

  # IMAGE VARIABLES
  DOCKER_IMAGE_APP: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  DOCKER_IMAGE_PHPFPM: $CI_REGISTRY_IMAGE:7.4.10-fpm-alpine3.11

Build Base:
  stage: build
  image: docker:20.10.5
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --no-cache -t $DOCKER_IMAGE_PHPFPM -f Dockerfile-Build .
    - docker push $DOCKER_IMAGE_PHPFPM
  # when: manual
  tags:
    - docker

Package Development:
  stage: package
  image: docker:20.10.5-git
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - mv .env.development .env
  script:
    - docker build --no-cache -t $DOCKER_IMAGE_APP -f Dockerfile-App .
    - docker push $DOCKER_IMAGE_APP
  tags:
    - docker

Deploy Development:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker stack deploy --orchestrator swarm -c docker-development.yml --with-registry-auth pln-marketplace
  # environment:
  #   name: URL Development
  #   url: http://dev-sinjai.air.id
  only:
    - branches
  tags:
    - site-dd
