stages:
  - build
  - package
  - deploy

variables:
  # CI VARIABLES
  CI_REGISTRY_USER: bkwh-registry
  CI_REGISTRY_PASSWORD: 3eYVgSfPu1YH4xp-XbQ2
  CI_REGISTRY: registry-iconx.air.id

  # DATASOURCE LOKI
  DATASOURCE_LOKI: http://10.14.204.239:20310/loki/api/v1/push

  # IMAGE VARIABLES
  DOCKER_IMAGE_BASE: $CI_REGISTRY_IMAGE:base
  DOCKER_IMAGE_APP: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  DOCKER_IMAGE_PHPFPM: registry-iconx.air.id/iconcash/latios:php-fpm-7.4.28-pgsql

Build Base:
  stage: build
  image: docker:20.10.5
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --no-cache -t $DOCKER_IMAGE_BASE --build-arg IMAGE_NAME=$DOCKER_IMAGE_PHPFPM -f docker/deployment/Dockerfile-Build .
    - docker push $DOCKER_IMAGE_BASE
  when: manual
  tags:
    - docker

Package Docker:
  stage: package
  image: docker:20.10.5
  services:
    - docker:20.10.5-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - >
      if [ "$CI_COMMIT_REF_NAME" == "development" ]; then
        cp .env.staging .env &&
        docker build --no-cache -t $DOCKER_IMAGE_APP --build-arg IMAGE_NAME=$DOCKER_IMAGE_BASE -f docker/deployment/Dockerfile-App . &&
        docker push $DOCKER_IMAGE_APP
      elif [ "$CI_COMMIT_REF_NAME" == "new-staging" ]; then
        cp .env.staging .env &&
        docker build --no-cache -t $DOCKER_IMAGE_APP --build-arg IMAGE_NAME=$DOCKER_IMAGE_BASE -f docker/deployment/Dockerfile-App . &&
        docker push $DOCKER_IMAGE_APP
      else
        cp .env.production .env &&
        docker build --no-cache -t $DOCKER_IMAGE_APP --build-arg IMAGE_NAME=$DOCKER_IMAGE_BASE -f docker/deployment/Dockerfile-App . &&
        docker push $DOCKER_IMAGE_APP
      fi
  rules:
    - if: '$CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "new-staging" || $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
  tags:
    - docker

Package k8s:
  stage: package
  image: docker:20.10.5
  services:
    - docker:20.10.5-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - >
      touch .env &&
      docker build --no-cache -t $DOCKER_IMAGE_APP --build-arg IMAGE_NAME=$DOCKER_IMAGE_BASE -f docker/deployment/Dockerfile-App . &&
      docker push $DOCKER_IMAGE_APP
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+-k8s$/'
  tags:
    - docker

Deploy DevStaging:
  stage: deploy
  script:
    - >
      if [ "$CI_COMMIT_REF_NAME" == "development" ]; then
        kubectl set image deployment/plnmkp-saruman plnmkp-saruman=$DOCKER_IMAGE_APP -n development
        kubectl rollout restart deployment/plnmkp-saruman -n development
      else
        kubectl set image deployment/plnmkp-saruman plnmkp-saruman=$DOCKER_IMAGE_APP -n staging
        kubectl rollout restart deployment/plnmkp-saruman -n staging
      fi
  only:
    - new-staging
  tags:
    - bkwh-runner

# https://stamkp.beyondkwh.id/api/core/

