version: "3.8"

networks:
  loadbalancer:
    external: true

services:
  pln-marketplace-saruman-production:
    image: $DOCKER_IMAGE_APP
    networks:
      - loadbalancer
    ports:
      - target: 80
        published: 8892
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nfs-logs/pln-marketplace-saruman-production:/var/www/html/storage/logs
    environment:
      - ELASTIC_APM_ENABLED=true
      - ELASTIC_APM_LOG_LEVEL_STDERR=INFO
      - ELASTIC_APM_LOG_LEVEL=TRACE
      - ELASTIC_APM_LOG_LEVEL_SYSLOG=TRACE
      - ELASTIC_APM_SERVER_URL=http://10.14.204.239:8200
      - ELASTIC_APM_SECRET_TOKEN=d1cd3a2b456907792bee56ffd0d43f34a86e42ee602c97763177218e0e23a86f
      - ELASTIC_APM_SERVER_TIMEOUT=30s
      - ELASTIC_APM_SERVICE_NAME=plnm-saruman-prod
      - ELASTIC_APM_SERVICE_VERSION=0.1
      - ELASTIC_APM_ENVIRONMENT=development
      - ELASTIC_APM_TRANSACTION_MAX_SPANS=1000
      - ELASTIC_APM_TRANSACTION_SAMPLE_RATE=1.0
      # - ELASTIC_APM_VERIFY_SERVER_CERT=false
      # - ELASTIC_APM_TRANSACTION_IGNORE_URLS=/swagger-resources*, /v2/api-docs*, /actuator*, /webjars/**, /swagger-ui.html
    logging:
      driver: none
    #  options:
    #    loki-url: "$DATASOURCE_LOKI"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.pln-marketplace-saruman-production.loadbalancer.server.port=80"
        - "traefik.http.middlewares.compress-pln-marketplace-saruman-production.compress=true"
        - "traefik.http.middlewares.redirectscheme-pln-marketplace-saruman-production.redirectscheme.scheme=https"
        - "traefik.http.middlewares.ratelimit-pln-marketplace-saruman-production.ratelimit.period=1s"
        - "traefik.http.middlewares.ratelimit-pln-marketplace-saruman-production.ratelimit.average=25"
        - "traefik.http.middlewares.ratelimit-pln-marketplace-saruman-production.ratelimit.burst=25"
        - "traefik.http.middlewares.stripprefix-local-pln-marketplace-saruman-production.stripprefix.prefixes=/api/plnmp/core"
        - "traefik.http.middlewares.stripprefix-public-pln-marketplace-saruman-production.stripprefix.prefixes=/v1/core"
        - "traefik.http.routers.local-pln-marketplace-saruman-production-web.rule=Host(`10.14.204.119`) && PathPrefix(`/api/plnmp/core`)"
        - "traefik.http.routers.local-pln-marketplace-saruman-production-web.middlewares=stripprefix-local-pln-marketplace-saruman-production,compress-pln-marketplace-saruman-production,ratelimit-pln-marketplace-saruman-production"
        - "traefik.http.routers.local-pln-marketplace-saruman-production-web.entrypoints=web"
        - "traefik.http.routers.public-pln-marketplace-saruman-production-web.rule=Host(`api-mkp.iconcash.id`) && PathPrefix(`/v1/core`)"
        - "traefik.http.routers.public-pln-marketplace-saruman-production-web.middlewares=redirectscheme-pln-marketplace-saruman-production"
        - "traefik.http.routers.public-pln-marketplace-saruman-production-web.entrypoints=web"
        - "traefik.http.routers.public-pln-marketplace-saruman-production-websecure.rule=Host(`api-mkp.iconcash.id`) && PathPrefix(`/v1/core`)"
        - "traefik.http.routers.public-pln-marketplace-saruman-production-websecure.middlewares=stripprefix-public-pln-marketplace-saruman-production,compress-pln-marketplace-saruman-production,ratelimit-pln-marketplace-saruman-production"
        - "traefik.http.routers.public-pln-marketplace-saruman-production-websecure.tls=true"
        - "traefik.http.routers.public-pln-marketplace-saruman-production-websecure.entrypoints=websecure"
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.plnmp == core
        preferences:
          - spread: node.labels.plnmp
      resources:
        limits:
          memory: 1G
