version: "3.8"

networks:
  loadbalancer:
    external: true

services:
  pln-marketplace-saruman-development:
    image: $DOCKER_IMAGE_APP
    networks:
      - loadbalancer
    # ports:
    #   - target: 80
    #     published: 8080
    #     protocol: tcp
    #     mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nfs-development/pln-marketplace-saruman-development/logs:/var/www/html/storage/logs
    logging:
      driver: loki
      options:
        loki-url: "$DATASOURCE_LOKI"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.ip == 10.14.204.125
        preferences:
          - spread: node.labels.ip
      resources:
        limits:
          memory: 512M
