version: "3.8"

networks:
  loadbalancer:
    external: true

services:
  pln-marketplace-saruman-evds:
    image: $DOCKER_IMAGE_EVDS
    networks:
      - loadbalancer
    # ports:
    #   - target: 80
    #     published: 8080
    #     protocol: tcp
    #     mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nfs-production/pln-marketplace-saruman-evds/logs:/var/www/html/storage/logs
    logging:
      driver: loki
      options:
        loki-url: "$DATASOURCE_LOKI"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.pln-marketplace-saruman-evds.loadbalancer.server.port=80"
        - "traefik.http.middlewares.redirectscheme-pln-marketplace-saruman-evds.redirectscheme.scheme=https"
        - "traefik.http.middlewares.compress-pln-marketplace-saruman-evds.compress=true"
        - "traefik.http.middlewares.stripprefix-public-pln-marketplace-saruman-evds.stripprefix.prefixes=/v1/core"
        - "traefik.http.routers.public-pln-marketplace-saruman-evds-web.rule=Host(`api-ev.iconcash.id`) && PathPrefix(`/v1/core`)"
        - "traefik.http.routers.public-pln-marketplace-saruman-evds-web.middlewares=redirectscheme-pln-marketplace-saruman-evds"
        - "traefik.http.routers.public-pln-marketplace-saruman-evds-web.entrypoints=web"
        - "traefik.http.routers.public-pln-marketplace-saruman-evds-websecure.rule=Host(`api-ev.iconcash.id`) && PathPrefix(`/v1/core`)"
        - "traefik.http.routers.public-pln-marketplace-saruman-evds-websecure.middlewares=stripprefix-public-pln-marketplace-saruman-evds,compress-pln-marketplace-saruman-evds"
        - "traefik.http.routers.public-pln-marketplace-saruman-evds-websecure.tls=true"
        - "traefik.http.routers.public-pln-marketplace-saruman-evds-websecure.entrypoints=websecure"
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.plnmp-ev == gandul
        preferences:
          - spread: node.labels.plnmp-ev
      resources:
        limits:
          memory: 512M
