ARG IMAGE_NAME
FROM $IMAGE_NAME

COPY --chown=www-data . /var/www/html/
WORKDIR /var/www/html

COPY ./docker/config/php.ini /usr/local/etc/php/php.ini
COPY ./docker/config/elastic_apm.ini /opt/elastic/apm-agent-php/etc/elastic-apm-custom.ini
COPY ./docker/config/fpm-pool.conf /usr/local/etc/php-fpm.d/03-fpm-pool.conf
COPY ./docker/config/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/config/nginx-site.conf /etc/nginx/sites-enabled/default
COPY ./docker/config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN composer update
# RUN php artisan swagger-lume:generate
RUN rm -Rf docker/
RUN chmod -R 775 /var/www/html/storage
RUN chown -R www-data:www-data /var/www/html/storage

EXPOSE 80
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
