ARG IMAGE_NAME

# Composer
FROM composer:2.1.8 as composer

# Build PHP FPM & NGINX
FROM $IMAGE_NAME

COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN apk update && \
    apk --no-cache --update add build-base autoconf curl-dev unzip zip git jq && \
    apk add --no-cache nginx supervisor ca-certificates zlib-dev libzip-dev oniguruma-dev postgresql-dev && \
    rm -rf /var/cache/apk/*

RUN docker-php-ext-install mysqli pgsql pdo pdo_mysql pdo_pgsql zip bcmath gd mbstring && \
    docker-php-ext-enable mysqli pgsql pdo pdo_mysql pdo_pgsql zip bcmath gd mbstring


COPY ./docker/config/php.ini /usr/local/etc/php/php.ini
COPY ./docker/config/fpm-pool.conf /usr/local/etc/php-fpm.d/fpm-pool.conf
COPY ./docker/config/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN rm -Rf /etc/nginx/conf.d/default.conf \
    && composer --version

EXPOSE 80
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

