FROM registry-iconx.air.id/iconcash/latios:php-fpm-7.4.28

COPY ./docker/config/fpm-pool.conf /usr/local/etc/php-fpm.d/03-fpm-pool.conf
COPY ./docker/config/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/config/nginx-site.conf /etc/nginx/sites-enabled/default
#COPY ./docker/config/elastic_apm.ini /usr/local/etc/php/conf.d/elastic_apm.ini
COPY ./docker/config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

COPY --chown=www-data . /var/www/html/

RUN composer install
RUN php artisan swagger-lume:generate
RUN rm -Rf /var/www/html/docker

EXPOSE 80
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

# COPY ./docker/config/php.ini /usr/local/etc/php/php.ini
# COPY ./docker/config/fpm-pool.conf /usr/local/etc/php-fpm.d/fpm-pool.conf
# COPY ./docker/config/nginx.conf /etc/nginx/nginx.conf
# COPY ./docker/config/nginx-site.conf /etc/nginx/sites-enabled/default
# COPY ./docker/config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
# COPY ./docker/config/elastic_apm.ini /usr/local/etc/php/conf.d/elastic_apm.ini