ARG IMAGE_NAME
FROM $IMAGE_NAME

COPY --chown=www-data . /var/www/html/
WORKDIR /var/www/html

COPY ./docker/config/elastic_apm.ini /usr/local/etc/php/conf.d/elastic_apm.ini
COPY ./docker/config/fpm-pool.conf /usr/local/etc/php-fpm.d/03-fpm-pool.conf
COPY ./docker/config/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/config/nginx-site.conf /etc/nginx/sites-enabled/default
COPY ./docker/config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN composer update
RUN php artisan swagger-lume:generate
RUN rm -Rf /var/www/html/docker

EXPOSE 80
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
