version: "3.8"

networks:
  loadbalancer:
    external: true

services:
  pln-marketplace-saruman-production:
    image: $DOCKER_IMAGE_APP
    networks:
      - loadbalancer
    ports:
      - target: 80
        published: 8892
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nfs-logs/pln-marketplace-saruman-production:/var/www/html/storage/logs
    environment:
      - ELASTIC_APM_ENABLED=true
      - ELASTIC_APM_LOG_LEVEL_STDERR=INFO
      - ELASTIC_APM_LOG_LEVEL=INFO
      - ELASTIC_APM_LOG_LEVEL_SYSLOG=INFO
      - ELASTIC_APM_SERVER_URL=http://10.14.204.123:9901
      - ELASTIC_APM_SECRET_TOKEN=yTt4JtctZKbbKfxTUboNWYWSD9jnUds7DQdQ9U9ogtSmTMdyA4mJ7YWg4KoJtMQT
      - ELASTIC_APM_SERVER_TIMEOUT=30s
      - ELASTIC_APM_SERVICE_NAME=plnmkp-core-api
      - ELASTIC_APM_SERVICE_VERSION=0.1
      - ELASTIC_APM_ENVIRONMENT=production
      - ELASTIC_APM_TRANSACTION_MAX_SPANS=1000
      - ELASTIC_APM_TRANSACTION_SAMPLE_RATE=1.0
      # - ELASTIC_APM_VERIFY_SERVER_CERT=false
      # - ELASTIC_APM_TRANSACTION_IGNORE_URLS=/swagger-resources*, /v2/api-docs*, /actuator*, /webjars/**, /swagger-ui.html
    logging:
      driver: none
    #  options:
    #    loki-url: "$DATASOURCE_LOKI"
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.plnmp == core
        preferences:
          - spread: node.labels.plnmp
      resources:
        limits:
          memory: 2G
          cpus: "2"
