version: "3.8"
networks:
  loadbalancer:
    external: true
services:
  pln-marketplace-saruman-staging:
    image: $DOCKER_IMAGE_APP
    networks:
      - loadbalancer
    extra_hosts:
      - "api-sandbox.plndigital.id:10.14.204.145"
      - "portalapp.iconpln.co.id:121.100.23.228"
    ports:
      - target: 80
        published: 8892
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nfs-logs/pln-marketplace-saruman-staging:/var/www/html/storage/logs
    # environment:
    #   - ELASTIC_APM_ENABLED=false
    #   - ELASTIC_APM_ENVIRONMENT=staging
    #   - ELASTIC_APM_LOG_LEVEL_STDERR=INFO
    #   - ELASTIC_APM_LOG_LEVEL=INFO
    #   - ELASTIC_APM_SERVER_URL=http://apm-server:8200
    #   - ELASTIC_APM_SECRET_TOKEN=SuperSecretT0k3n
    #   - ELASTIC_APM_SERVICE_NAME=plnmkp-core-api
    #   - ELASTIC_APM_VERIFY_SERVER_CERT=false
    logging:
      driver: loki
      options:
        loki-url: "$DATASOURCE_LOKI"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.ip == 10.14.204.125
        preferences:
          - spread: node.labels.ip
      resources:
        limits:
          memory: 2G
          cpus: "2"
