# Composer
FROM composer:2.1.8 as composer

# Build PHP FPM & NGINX
# FROM php:7.4.25-fpm-alpine3.13
FROM php:7.4.28-fpm-alpine3.15

RUN apk update && \
    apk --no-cache --update add build-base autoconf curl-dev unzip zip git jq && \
    apk add --no-cache nginx supervisor ca-certificates zlib-dev libzip-dev oniguruma-dev postgresql-dev && \
    rm -rf /var/cache/apk/*

RUN docker-php-ext-install mysqli pgsql pdo pdo_mysql pdo_pgsql zip bcmath mbstring && \
    docker-php-ext-enable mysqli pgsql pdo pdo_mysql pdo_pgsql zip bcmath mbstring

RUN mkdir -p /home/apm-agent && \
    cd /home/apm-agent && \
    git clone https://github.com/elastic/apm-agent-php.git apm && \
    cd apm/src/ext && \
    /usr/local/bin/phpize && ./configure --enable-elastic_apm && \
    make clean && make && make install

COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN rm -Rf /etc/nginx/conf.d/default.conf && composer --version
RUN rm -Rf /usr/local/etc/php-fpm.d/zz-docker.conf
RUN mv /usr/local/etc/php-fpm.d/docker.conf /usr/local/etc/php-fpm.d/01-docker.conf
RUN mv /usr/local/etc/php-fpm.d/www.conf /usr/local/etc/php-fpm.d/02-www.conf

COPY ./docker/config/php.ini /usr/local/etc/php/php.ini
COPY ./docker/config/elastic_apm.ini /usr/local/etc/php/conf.d/elastic_apm.ini
COPY ./docker/config/fpm-pool.conf /usr/local/etc/php-fpm.d/03-fpm-pool.conf
COPY ./docker/config/nginx.conf /etc/nginx/nginx.conf
